-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM BOOK A
JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES AS C ON A.BOOK_ID = C.BOOK_ID
WHERE MONTH(C.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_NAME
ORDER BY A.AUTHOR_ID, CATEGORY DESC