-- 코드를 입력하세요


SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I, ANIMAL_OUTS O,
    (SELECT I.ANIMAL_ID, DATEDIFF(O.DATETIME, I.DATETIME) AS DATE_DIFF
    FROM ANIMAL_INS I, ANIMAL_OUTS O
    WHERE I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATE_DIFF DESC
    LIMIT 2) RESULT
WHERE I.ANIMAL_ID = O.ANIMAL_ID
    AND I.ANIMAL_ID = RESULT.ANIMAL_ID

