-- 코드를 입력하세요
WITH CAN_NOT AS (
    SELECT C.CAR_ID	
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE END_DATE >= "2022-11-01"
        AND START_DATE <= "2022-11-30"
)

SELECT H.CAR_ID,
    C.CAR_TYPE,
    FLOOR(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID NOT IN (SELECT * FROM CAN_NOT)
    AND DURATION_TYPE = "30일 이상"
GROUP BY H.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000 
ORDER BY 3 DESC, 2, 1 DESC