-- 코드를 입력하세요
WITH JOINED_PEOPLE AS (SELECT USER_ID
FROM USER_INFO 
WHERE YEAR(JOINED) = "2021")

SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT J.USER_ID) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT J.USER_ID) / (SELECT COUNT(*) FROM JOINED_PEOPLE), 1) PUCHASED_RATIO
# SELECT *
FROM JOINED_PEOPLE J
    JOIN ONLINE_SALE O ON J.USER_ID = O.USER_ID
GROUP BY 1, 2
ORDER BY 1, 2
