-- 코드를 입력하세요
WITH JOINED AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM JOINED), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE 
WHERE USER_ID IN (SELECT * FROM JOINED)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH