-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF F
    JOIN (SELECT SUM(TOTAL_ORDER) JULY_TOTAL, J.FLAVOR
        FROM JULY J
        GROUP BY FLAVOR) JJ ON F.FLAVOR = JJ.FLAVOR
GROUP BY F.FLAVOR
ORDER BY JULY_TOTAL+SUM(F.TOTAL_ORDER) DESC
LIMIT 3