-- 코드를 입력하세요
WITH RECURSIVE CTE (N) AS (
    SELECT 0
    UNION
    SELECT N+1 FROM CTE WHERE N < 23
)

SELECT N AS HOUR,
    COUNT(ANIMAL_ID) AS "COUNT"
FROM CTE C
    LEFT JOIN ANIMAL_OUTS ON N = HOUR(DATETIME)
GROUP BY n
ORDER BY n