-- 코드를 입력하세요

WITH CNT_REVIEW AS (
    SELECT MEMBER_ID, COUNT(*) MANY
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY MANY DESC
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE MP
    JOIN REST_REVIEW RE ON MP.MEMBER_ID = RE.MEMBER_ID
WHERE RE.MEMBER_ID IN (SELECT MEMBER_ID FROM CNT_REVIEW)
ORDER BY REVIEW_DATE, REVIEW_TEXT

