-- 코드를 입력하세요

WITH MANY AS (
    SELECT MEMBER_ID, COUNT(*) CNT
    FROM REST_REVIEW 
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 1
)


SELECT MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
    JOIN MANY M ON P.MEMBER_ID = M.MEMBER_ID
ORDER BY 3, 2
