-- 코드를 작성해주세요
WITH SKILLS AS (
    SELECT SUM(CODE) SKILL_CODE
    FROM SKILLCODES
    WHERE NAME IN ("Python", "C#")
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SKILL_CODE FROM SKILLS)
ORDER BY ID