-- 코드를 작성해주세요

WITH SCORE_EMP AS(
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)


SELECT SCORE, 
    S.EMP_NO,
    EMP_NAME,	
    POSITION,
    EMAIL
FROM SCORE_EMP S
    LEFT JOIN HR_EMPLOYEES E ON S.EMP_NO = E.EMP_NO
    JOIN HR_DEPARTMENT D ON D.DEPT_ID = E.DEPT_ID