-- 코드를 입력하세요

WITH MAX_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) MXP
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)


SELECT F.CATEGORY,
    PRICE,
    PRODUCT_NAME
FROM FOOD_PRODUCT F
    JOIN MAX_PRICE M ON F.CATEGORY = M.CATEGORY 
WHERE PRICE = MXP
ORDER BY 2 DESC