-- 코드를 작성해주세요

SELECT 
    CASE WHEN SKILL_CODE & ( SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = "PYTHON") 
            AND SKILL_CODE & ( SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = "FRONT END")         
        THEN "A" 
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = "C#") THEN "B"
    WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = "FRONT END") THEN "C"
    END AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS 
HAVING GRADE IS NOT NULL
ORDER BY 1, 2